version: '3.5'

services:
  #########################
  mongo:
    container_name: clinic-db
    image: mongo:6
    restart: always
    hostname: ${MONGO_HOST_NAME}
    volumes:
      - ${MONGO_DATA}:/data/db
      - ${MONGO_DUMP}:/dump
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - clinic-network
  #########################
  app:
    container_name: clinic-api
    build:
      context: .
      dockerfile: ./dockerfile
    restart: always
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - clinic-network

networks:
  clinic-network:
    driver: bridge
