services:
  #########################
  mongo:
    container_name: doctor-db
    image: mongo:8-noble
    restart: always
    hostname: ${MONGO_HOST_NAME}
    volumes:
      - ${MONGO_DATA}:/data/db
      - ${MONGO_DUMP}:/dump
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - doctor-network
  #########################
  app:
    container_name: doctor-app
    build:
      context: .
      dockerfile: ./dockerfile
    restart: always
    env_file: .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - doctor-network
#########################
networks:
  doctor-network:
    driver: bridge
