name: Feature Implementation
description: Template for tracking feature implementation tasks
title: "[Feature]: "

body:
  - type: markdown
    attributes:
      value: "# What needs to be done"

  - type: checkboxes
    id: required-tasks
    attributes:
      label: "foo"
      options:
        - label: Update the README file
        - label: Update swagger API documentation
        - label: At least one e2e test should pass

  - type: textarea
    id: additional-tasks
    attributes:
      label: "foo"
      description: Add additional tasks if needed
      placeholder: "- [ ] Additional task"

  - type: markdown
    attributes:
      value: "# What is optional to be done"

  - type: textarea
    id: optional-tasks
    attributes:
      label: "foo"
      placeholder: List optional tasks here

  - type: markdown
    attributes:
      value: "# Constraints"

  - type: textarea
    id: constraints
    attributes:
      label: "foo"
      placeholder: List constraints here