export default {
  ACCESS_TOKEN_ADMINISTRATIVE: 'ACCESS_TOKEN_ADMINISTRATIVE',
  REFRESH_TOKEN_ADMINISTRATIVE: 'REFRESH_TOKEN_ADMINISTRATIVE',
  ACCESS_TOKEN_PATIENT: 'ACCESS_TOKEN_PATIENT',
  REFRESH_TOKEN_PATIENT: 'REFRESH_TOKEN_PATIENT',
};
